### ISSUE TITLE
Need some sort of changelog

### ISSUE THREAD

**Issue by taylorzr** [taylorzr/verbalize#21]
Best practices for this?

**Comment by wakproductions** [comment]
I maintain a `CHANGELOG.md` file in the base directory of all my gems. Look at the `credit_line_interactor` gem. Seems how most other maintainers do it.

**Comment by taylorzr** [comment]
This seems like a pretty solid standard: 
- http://keepachangelog.com/en/0.3.0/
- https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by taylorzr** [comment]
This is done
