### ISSUE TITLE
Thoughts on more flexible input

### ISSUE THREAD

**Issue by taylorzr** [taylorzr/verbalize#24]
### Current style
```ruby
class SomeAction
  include Verbalize::Action

  input :a, :b, optional: :c
end
```
We currently don't allow defining defaults in the input signature. This is partly because when using something like `input a: SomeClass.new`, *:a* will refer to the same instance of *SomeClass* on each call of *SomeAction*. This is because input is evaluated only once at load time.

### Grape style
Something like [grapes parameter handling](https://github.com/ruby-grape/grape#parameter-validation-and-coercion) would be much more flexible.
```ruby
class SomeAction
  include Verbalize::Action

  input do
    requires :a # maybe `requires :a, :b`
    requires :b
    optional :c
  end
end
```
Using an input block would allow us to know when defining input is done. This is important because the way Verbalize current works, is that we do all the magic when `.input` is called. So if right now, we naively used separate calls for input, we would be overriding previous input, not appending to it.

My first thought was that this feels like overkill because unlike an api or cli interface, we're not doing type coercion. But it would allow us much more flexibility in defining input, and would make defaults possible. For example, we could have defaults.

```ruby
class SomeAction
  include Verbalize::Action

  input do
    requires :a, :b
    # Maybe we can define multiple optional keys with defaults when their defaults are value objects
    optional c: true, d: true
   # And entity objects would be defined one at a time, and given a block or a callable
    optional :e { SomeClass.new }
    optional :e, -> { SomeClass.new }
  end
end
```

We could also skip using an input block, and do the Verbalize magic on each input call. For example:
```ruby
class SomeAction
  include Verbalize::Action

  requires :a # store :a as an input and do Verbalize magic
  requires :b # store :b as input and do Verbalize magic again for both :a & :b
end
```

This would work but I think it's pretty hacky, so I'd probably prefer the block implementation even though it's a little more verbose.

Thoughts @Kuraiou @tmertens?

**Comment by Kuraiou** [comment]
One of the chief values of Verbalize is its lack of verbosity (amusingly enough). I would not like the block definition format if it were the required format (not to mention we can't break the current API because people are using Verbalize as a public gem). Writing this as a new format seems reasonable -- people are familiar with the general structure -- but I'd still prefer something that's a little more "extension"-like (i.e. new method) or "tweak"-like (i.e. small change to existing params) e.g., as discussed earlier:

```ruby
class SomeAction
  include Verbalize::Action
  # key/val optionals w/defaults at end of list, lazy-call lambda defaults
  input :a, :b, optional: [:c, d: ->() { DateTime.current }]
end

# or
class SomeAction
  include Verbalize::Action
  # key/val optionals w/defaults at end of list, lazy-call lambda defaults
  input :a, :b, optional: [:c, :d]
  # separate `default` method, same logic as above
  default {
    c: ->() { DateTime.current },
    d: true
  }
end
```

**however** I wouldn't complain if you implemented block definition style. I would just be wary about making sure existing behavior continues to work..

**Comment by taylorzr** [comment]
Yea I'm not talking about breaking current implementation, just what would be best in the long run.

This looks good to me, we could even add it as backwards compatible feature. We could also even implement it with the default taking any callable object. 
```ruby
class SomeAction
  include Verbalize::Action

  input :a, :b, optional: [:c, d: -> { DateTime.current }]
end
```

Maybe we should start there, and think about a different interface if it comes up as a requirement in the future.

**Comment by taylorzr** [comment]
Thinking about this a bit more. The problem with `input :a, :b, optional: [:c, d: -> { DateTime.current }]` is that how do we know when to evaluate a default? 

If we say we evaluate a default when the default is callable, then we have excluded actions from using anything callable as input, because it will be called by verbalize.

The `input do ... end` format might be a better choice. We could also add on support for this block format on top of existing non block format. For example, an action input could be defined as:
```ruby
input :a, :b
```
or 
```ruby
input do
  requires :a, :b
end
```
But not a combination or both.

**Comment by Kuraiou** [comment]
? you would evaluate the default when the variable method is called inside of `call`. the default would only execute if you didn't provide it as an input.

As I understand it, all you would need to do is:
1. store the defaults associated with the keys
2. change `attribute_readers_string` to exclude optional inputs with defaults
3. underneath `#{attribute_readers_string}` in `Build#call`, map the optionals:
    ```ruby
    #{optional_default_attributes_string}
    ...
    def optional_default_attributes_string
      inputs_with_defaults.map do |input|
        <<-CODE
          def #{input}
            return @#{input} unless @#{input}.nil?
            self.class.defaults[:#{input}].call
          end
        CODE
      end.join("\n\n")
    end
    ```

**Comment by Kuraiou** [comment]
But I also don't have any problem with the `do` block format.

**Comment by taylorzr** [comment]
Ah so I think the confusion is that I'm thinking about the default value as optionally a proc, where as you might be saying it should just always be a proc.

I.e. If it were optionally a proc, where either of these is valid:
```ruby
input optional a: 2
end
```
```ruby
input optional a: -> { 2 }
```

We wouldn't be able to pass in anything callable as a optional input, because AFAIK, the only way to know if we should evaluate the optional argument at run time would be to evaluate it if it responds to call.

So like if we wanted to pass in say another action as optional input, but we wanted the action to be the input, not the result of the call of the action, then this would be impossible.

So yea, if we don't do this, and instead limit optional defaults to only procs, then we would always just call the proc and get a value for the optional.

---

Or as I'm writing this I realized that we could pass in any callable itself by just wrapping it in a proc, e.g.
```ruby
input optional: { some_action: -> { SomeAction } }
```

So this isn't really a problem either way :/

**Comment by Kuraiou** [comment]
*or* you could wrap non-callables in a callable at construction time. there's lots of possibilities here ;)

**Comment by taylorzr** [comment]
I would consider this issue resolved when https://github.com/taylorzr/verbalize/pull/30 merges

**Comment by Kuraiou** [comment]
I will update based on your feedback and ping you again once that's ready.
