### ISSUE TITLE
Required Inputs: nil check

### ISSUE THREAD

**Issue by tremulaes** [taylorzr/verbalize#32]
If I declare an input and pass the keyword through with `nil` as the value, it fails silently. It would be nice if I could flag a Verbalize::Action to do a nil check of some sort against all required inputs. I'm not sure what would be the best interface for that, but if we can decide on something, I'll be happy to put in a PR.

```
class Calculate
  include Verbalize::Action

  input :a, :b, optional: [:c]

  def call
    ...
  end
end

result = Calculate.call(a: 5, b: nil)
result.success? # true
```

Unless the code internally does explicit nil checking, i could run ahead thinking it was successful; this is especially troublesome with side-effect actions that may end up creating records with missing relations (where they're not DB required but they should be here). Having an up-front nil check on `.call` and `.call!` could also give a nice error.

The one issue I see with this is that it diverges from how Ruby keyword args handle nil, which is why I'd prefer to see it as an optional behavior, as opposed to the default. [Grape has something similar](https://github.com/ruby-grape/grape#built-in-validators) which I am a fan of as an option. 

Some ideas for the interface:

```
class Calculate
  include Verbalize::Action

  input :a, :b, optional: [:c], allow_blank: false
end
```
```
class Calculate
  include Verbalize::Action

  input allow_blank: [:a, :b], optional: [:c]
end
```
```
class Calculate
  include Verbalize::Action

  input :a, :b, optional: [:c]

  def call
    fail_missing_inputs!
  end
end
```

**Comment by secade** [comment]
@taylorzr @Kuraiou

**Comment by secade** [comment]
Another thought:

Have a separate class that provides a heavier input interface a little more similar to Grape that allows for things like type-checking (coercion probably isn't necessary):

```
class Calculation
  include Verbalize::ActionWithValidation
end
```

You could implement the inputs block that is being discussed over at #24 without muddying up the nice slimness of the current `Verbalize::Action` class.

**Comment by taylorzr** [comment]
There are validations as of verbalize 2.3.0 thanks @Kuraiou
