### ISSUE TITLE
`call!` stubbing in test is inconsistent

### ISSUE THREAD

**Issue by tmertens** [taylorzr/verbalize#7]
Stubbing the `call!` method in tests will result in inconsistent behavior depending on what the calling class is.

When the calling class is another Verbalize interactor, stubbing `call!` to `throw :verbalize_error` works as expected.

When the calling class is a generic class, stubbing `call!` to `throw :verbalize_error` will result in an UncaughtThrowError being thrown, instead of a VerbalizeError.  So, if the calling class or something above it rescues `VerbalizeError` (although you shouldn't use exception handling for control flow, you should use `call` instead), then it will fail to rescue the error in test unless you raise `VerbalizeError` specifically instead of stubbing the interactor to `throw`.

It would be ideal to have a single, unified method to stub behavior on Verbalize interactors in test so that we do not need to have multiple different methods of stubbing behavior in test for `call` and `call!`, with additional variations based on the type of caller.

**Comment by tmertens** [comment]
This will be resolved in Verbalize v2.0, see #12.

**Comment by taylorzr** [comment]
👍
